 name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-20.04  # Especifica 'ubuntu-20.04' para usar Ubuntu 20.04

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm install  # Instala las dependencias

    - run: npm run build --if-present  # Compila el código (si el script está presente en package.json)

    - run: npm test  # Ejecuta las pruebas

